import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../providers/language_provider.dart';

abstract final class AppTranslator {
  static const _english = <String, String>{
    'AI học tập': 'AI Study',
    'AI Study Assistant': 'AI Study Assistant',
    'Bạn cần đồng ý với điều khoản để tiếp tục.':
        'You need to accept the terms to continue.',
    'Bạn vừa đi hết bộ thẻ. Những thẻ chưa nhớ sẽ được ưu tiên ở lần ôn tiếp theo.':
        'You finished this set. Forgotten cards will be prioritized next time.',
    'Bằng cách tiếp tục, bạn đồng ý với Điều khoản sử dụng.':
        'By continuing, you agree to the Terms of Use.',
    'Bắt đầu bộ thẻ đầu tiên': 'Create your first set',
    'Bắt đầu miễn phí và đồng bộ tiến độ trên mọi thiết bị.':
        'Start free and sync progress across your devices.',
    'Bật đồng hồ': 'Enable timer',
    'Bộ flashcard': 'Flashcard sets',
    'Bộ flashcard cần ít nhất một thẻ.':
        'A flashcard set needs at least one card.',
    'Bộ flashcard học tập': 'Study flashcard set',
    'Bộ thẻ chưa có nội dung': 'This set has no cards yet',
    'Bộ thẻ gần đây': 'Recent flashcard sets',
    'Bút': 'Pen',
    'Các tin nhắn hiện tại sẽ được xóa khỏi màn hình.':
        'Current messages will be removed from this screen.',
    'Cài đặt': 'Settings',
    'Cần thêm dữ kiện': 'More context needed',
    'Cập nhật ghi chú': 'Update note',
    'Câu tiếp theo': 'Next question',
    'Chạm để lật · Vuốt để chuyển thẻ': 'Tap to flip · Swipe to move',
    'Chạm để quay lại thuật ngữ': 'Tap to return to the term',
    'Chạm vào thẻ để xem đáp án': 'Tap the card to reveal the answer',
    'Chào mừng\ntrở lại.': 'Welcome\nback.',
    'Chế độ học': 'Study mode',
    'Chế độ tối': 'Dark mode',
    'Chỉ bạn và người được mời có thể xem':
        'Only you and invited people can view',
    'Chi tiết bộ thẻ': 'Set details',
    'Chia sẻ': 'Share',
    'Chia sẻ bộ thẻ': 'Share set',
    'Chia sẻ quyền xem': 'Share view access',
    'Chỉnh sửa': 'Edit',
    'Chỉnh sửa bộ thẻ': 'Edit flashcard set',
    'Chỉnh sửa hồ sơ': 'Edit profile',
    'Chỉnh sửa thẻ': 'Edit card',
    'Chỉnh sửa thông tin': 'Edit information',
    'Chính xác!': 'Correct!',
    'CHỌN ĐỊNH NGHĨA ĐÚNG': 'CHOOSE THE CORRECT DEFINITION',
    'Chọn ngôn ngữ': 'Choose language',
    'Chủ đề': 'Subject',
    'Chủ sở hữu chưa thêm nội dung vào bộ này.':
        'The owner has not added cards to this set yet.',
    'Chưa chia sẻ riêng với tài khoản nào.':
        'Not shared directly with any account yet.',
    'Chưa có bộ thẻ': 'No flashcard sets yet',
    'Chưa có ghi chú nào': 'No notes yet',
    'Chưa có tài khoản?': 'No account yet?',
    'Chưa có thẻ để học': 'No cards to study',
    'Chưa mở được sổ tay': 'Could not open notes',
    'Chưa mở khóa': 'Locked',
    'Chưa nhớ': 'Forgotten',
    'Chưa tải được danh sách chia sẻ.': 'Could not load sharing list.',
    'Chưa tải được Dashboard': 'Could not load dashboard',
    'Chưa tải được nội dung': 'Could not load content',
    'Chưa thể cập nhật bộ thẻ.': 'Could not update the set.',
    'Chưa thể cập nhật thẻ lúc này.': 'Could not update the card now.',
    'Chưa thể lưu bộ thẻ. Vui lòng thử lại.':
        'Could not save the set. Please try again.',
    'Chưa thể lưu ghi chú. Vui lòng thử lại.':
        'Could not save the note. Please try again.',
    'Chưa thể lưu thẻ. Vui lòng thử lại.':
        'Could not save the card. Please try again.',
    'Chưa thể tạo bài quiz': 'Could not create quiz',
    'Chưa thể tạo tài khoản. Vui lòng thử lại.':
        'Could not create the account. Please try again.',
    'Chưa thể thay đổi quyền riêng tư.': 'Could not change privacy.',
    'Chưa thể xóa bộ thẻ lúc này.': 'Could not delete the set now.',
    'Chưa thể xóa ghi chú lúc này.': 'Could not delete the note now.',
    'Chưa thể xóa thẻ lúc này.': 'Could not delete the card now.',
    'Chưa tìm kiếm được': 'Search unavailable',
    'Công khai': 'Public',
    'Công nghệ': 'Technology',
    'Của bạn': 'Yours',
    'Đã cập nhật bộ thẻ.': 'Flashcard set updated.',
    'Đã cấp quyền xem.': 'View access granted.',
    'Đã có tài khoản?': 'Already have an account?',
    'Đã lưu nháp': 'Draft saved',
    'Đã lưu thay đổi.': 'Changes saved.',
    'Đã lưu vào sổ tay.': 'Saved to notes.',
    'Đã nhớ': 'Remembered',
    'Đã tạo bộ flashcard mới.': 'New flashcard set created.',
    'Đã thêm thẻ mới.': 'New card added.',
    'Đã thu hồi quyền truy cập.': 'Access revoked.',
    'Đã xóa bộ thẻ.': 'Flashcard set deleted.',
    'Đã xóa ghi chú.': 'Note deleted.',
    'Đã xóa thẻ.': 'Card deleted.',
    'Đang chỉnh sửa ghi chú của bạn': 'Editing your note',
    'Đang chuẩn bị không gian học tập': 'Preparing your study space',
    'Đang có quyền truy cập': 'People with access',
    'Đăng ký': 'Register',
    'Đang lưu...': 'Saving...',
    'Đăng nhập': 'Sign in',
    'Đang tìm trong bộ thẻ, từng thẻ nhớ và ghi chú...':
        'Searching sets, cards, and notes...',
    'Đăng xuất': 'Sign out',
    'Đăng xuất?': 'Sign out?',
    'Danh sách từ vựng': 'Card list',
    'Điều khoản sử dụng và Chính sách riêng tư':
        'Terms of Use and Privacy Policy',
    'Đính kèm ghi chú': 'Attach note',
    'ĐỊNH NGHĨA': 'DEFINITION',
    'Định nghĩa hoặc câu trả lời': 'Definition or answer',
    'Dữ liệu học tập của riêng bạn': 'Your private learning data',
    'Đúng hôm nay': 'Correct today',
    'Được chia sẻ': 'Shared',
    'Được tính từ các phiên học bạn đã hoàn thành':
        'Calculated from your completed study sessions',
    'Email': 'Email',
    'Email chưa đúng định dạng': 'Invalid email format',
    'Email hoặc mật khẩu chưa đúng. Bạn thử lại nhé.':
        'Incorrect email or password. Please try again.',
    'Email người nhận': 'Recipient email',
    'Flashcard, ghi chú và trợ lý AI trong một không gian học tập tập trung.':
        'Flashcards, notes, and AI in one focused study space.',
    'Gần đúng rồi': 'Almost there',
    'Ghi chú': 'Notes',
    'Ghi chú chưa đặt tên': 'Untitled note',
    'Ghi chú đã lưu': 'Saved notes',
    'Ghi chú được chia sẻ ở chế độ chỉ đọc': 'This shared note is read-only',
    'Ghi chú mới': 'New note',
    'Ghi chú viết tay': 'Handwritten note',
    'Ghi lại điều đáng nhớ': 'Capture what matters',
    'Ghi nhớ': 'Remember',
    'Ghi nhớ sâu hơn. Học tập tinh tế hơn.':
        'Remember deeply. Study beautifully.',
    'Giải thích, tóm tắt và tạo quiz': 'Explain, summarize, and create quizzes',
    'Giảm chói khi học trong môi trường tối':
        'Reduce glare in low-light environments',
    'Giữ lại': 'Keep',
    'Gửi': 'Send',
    'Gửi hướng dẫn': 'Send instructions',
    'Hãy kiểm tra backend và migration dữ liệu rồi thử lại.':
        'Check the backend and database migration, then try again.',
    'Hãy kiểm tra backend và thử lại.': 'Check the backend and try again.',
    'Hãy kiểm tra kết nối và thử tải lại.':
        'Check your connection and try again.',
    'Hãy liên hệ thuật ngữ với định nghĩa này để ghi nhớ lâu hơn.':
        'Connect the term with this definition to remember it longer.',
    'Hãy thêm ít nhất một thẻ trước khi bắt đầu học.':
        'Add at least one card before studying.',
    'Hãy thêm nội dung vào bộ flashcard rồi quay lại.':
        'Add cards to this set, then come back.',
    'Hãy thêm thẻ trước khi tạo bài quiz.': 'Add cards before creating a quiz.',
    'Hồ sơ': 'Profile',
    'Hồ sơ học tập': 'Study profile',
    'Họ và tên': 'Full name',
    'Hoàn tác': 'Undo',
    'Hoàn tất': 'Done',
    'Hoàn thành bài quiz': 'Quiz complete',
    'Hoàn thành hôm nay': 'Daily goal complete',
    'Hoàn thành phiên học': 'Study session complete',
    'Hoạt động hôm nay': 'Today’s activity',
    'Học lại': 'Study again',
    'Học ngay': 'Study now',
    'Hỏi AI về bài học của bạn...': 'Ask AI about your lesson...',
    'Hơi nhớ': 'Learning',
    'Hôm nay bạn muốn\nhọc điều gì?': 'What would you like\nto study today?',
    'Hủy': 'Cancel',
    'Kết nối đang gián đoạn. Bạn thử lại nhé.':
        'The connection was interrupted. Please try again.',
    'Kết nối đang gián đoạn. Hãy thử lại.':
        'The connection was interrupted. Try again.',
    'Kết quả được lọc ngay theo tiêu đề, nội dung và người tạo.':
        'Results are filtered instantly by title, content, and creator.',
    'Kết quả xuất hiện ngay bên dưới ô tìm kiếm':
        'Results appear directly below the search field',
    'Khác': 'Other',
    'Khó': 'Difficult',
    'Khoa học': 'Science',
    'Không có đáp án phù hợp': 'No suitable answer',
    'Không có kết quả': 'No results',
    'Không thể mở thư viện': 'Could not open library',
    'Không tìm thấy bộ thẻ': 'Flashcard set not found',
    'Không tìm thấy ghi chú': 'Note not found',
    'Không tìm thấy tài khoản hoặc chưa thể chia sẻ.':
        'Account not found or sharing is unavailable.',
    'Không tìm thấy trong dữ liệu của bạn, nội dung được chia sẻ hoặc công khai.':
        'Nothing found in your private, shared, or public content.',
    'Khu vực đính kèm đã sẵn sàng để kết nối.':
        'The attachment area is ready to connect.',
    'Kiến thức của bạn,\nđược tổ chức đẹp đẽ.':
        'Your knowledge,\nbeautifully organized.',
    'Kinh tế': 'Economics',
    'Làm lại': 'Redo',
    'Lưu bộ flashcard': 'Save flashcard set',
    'Lưu ghi chú': 'Save note',
    'Lưu thay đổi': 'Save changes',
    'Lưu thẻ': 'Save card',
    'Mặc định chỉ bạn nhìn thấy. Người được chia sẻ chỉ có quyền xem và học.':
        'Private by default. Shared recipients can only view and study.',
    'Mật khẩu': 'Password',
    'Mật khẩu cần ít nhất 6 ký tự': 'Password must be at least 6 characters',
    'Mật khẩu xác nhận chưa khớp': 'Passwords do not match',
    'MẶT SAU': 'BACK',
    'MẶT TRƯỚC': 'FRONT',
    'Màu nhận diện': 'Set color',
    'Mình có thể giải thích khái niệm, tạo flashcard, tạo quiz hoặc tóm tắt ghi chú.':
        'I can explain concepts, create flashcards and quizzes, or summarize notes.',
    'Mở ghi chú': 'Open notes',
    'Mô tả': 'Description',
    'Mở thư viện': 'Open library',
    'Mọi người có thể tìm thấy tài nguyên này.':
        'Everyone can discover this resource.',
    'Mọi tài khoản có thể tìm và xem': 'Every account can find and view',
    'Một câu giúp ghi nhớ theo ngữ cảnh':
        'A sentence that helps you remember in context',
    'Một khái niệm khác': 'Another concept',
    'Một thẻ tốt nên ngắn gọn ở mặt trước và rõ ràng ở mặt sau.':
        'A good card has a concise front and a clear back.',
    'Mục tiêu hoặc nội dung chính của bộ thẻ':
        'Goal or main content of this set',
    'Ngoại ngữ': 'Languages',
    'Ngôn ngữ': 'Language',
    'Người học': 'Learner',
    'Nhập email đã đăng ký. Chúng tôi sẽ gửi hướng dẫn khi tính năng được kết nối.':
        'Enter your registered email. We will send instructions when this feature is connected.',
    'Nội dung mặt sau': 'Back content',
    'Nội dung mặt trước': 'Front content',
    'Nội dung thẻ': 'Card content',
    'Ở lại': 'Stay',
    'Phát âm': 'Pronounce',
    'Quên mật khẩu?': 'Forgot password?',
    'Quiz': 'Quiz',
    'Riêng tư': 'Private',
    'Sẵn sàng hỗ trợ': 'Ready to help',
    'Sổ tay học tập': 'Study notebook',
    'Tài nguyên đã chuyển về riêng tư.': 'Resource changed to private.',
    'Tạo bộ đầu tiên hoặc mở một bộ được chia sẻ với bạn.':
        'Create your first set or open one shared with you.',
    'Tạo bộ flashcard': 'Create flashcard set',
    'Tạo bộ flashcard đầu tiên để bắt đầu học có hệ thống.':
        'Create your first set to start studying systematically.',
    'Tạo bộ thẻ': 'Create set',
    'Tạo bộ thẻ hoặc mở nội dung được chia sẻ':
        'Create a set or open shared content',
    'Tạo không gian\nhọc của riêng bạn.': 'Create your own\nstudy space.',
    'Tạo tài khoản': 'Create account',
    'Tạo tài khoản mới': 'Create a new account',
    'Tạo tài khoản thành công. Hãy đăng nhập!':
        'Account created. Please sign in!',
    'Tạo trang viết đầu tiên để lưu lại ý tưởng và kiến thức.':
        'Create your first page to save ideas and knowledge.',
    'Tất cả': 'All',
    'Tắt đồng hồ': 'Disable timer',
    'Tẩy': 'Eraser',
    'Tên bộ flashcard': 'Flashcard set name',
    'Tên bộ thẻ': 'Set name',
    'Tên bộ thẻ không được để trống': 'Set name is required',
    'Thành tích': 'Achievements',
    'Thẻ': 'Card',
    'Thẻ đã học': 'Cards learned',
    'Thẻ đã thực sự học': 'Cards actually learned',
    'Thẻ nhớ': 'Flashcards',
    'Thêm hình ảnh': 'Add image',
    'Thêm mô tả hoặc ghi chú dạng text...': 'Add a description or text note...',
    'Thêm thẻ': 'Add card',
    'Thêm thẻ đầu tiên': 'Add first card',
    'Thêm thẻ khác': 'Add another card',
    'Thêm thẻ mới': 'Add new card',
    'Thêm thuật ngữ đầu tiên để bắt đầu phiên học.':
        'Add the first term to begin studying.',
    'Thông tin bộ thẻ': 'Set information',
    'Thu hồi quyền': 'Revoke access',
    'Thử lại': 'Try again',
    'Thử tìm kiếm bằng một từ khóa khác.': 'Try a different keyword.',
    'Thư viện đang trống': 'Your library is empty',
    'Thư viện flashcard': 'Flashcard library',
    'THUẬT NGỮ': 'TERM',
    'Thuật ngữ hoặc câu hỏi': 'Term or question',
    'Tiến độ đã đồng bộ vẫn được lưu an toàn trong tài khoản.':
        'Your synced progress remains safely stored in your account.',
    'Tiếp tục hành trình học tập của bạn.': 'Continue your learning journey.',
    'TIẾP TỤC HỌC': 'CONTINUE STUDYING',
    'Tiêu đề ghi chú': 'Note title',
    'Tìm bộ thẻ, thuật ngữ hoặc ghi chú...': 'Search sets, terms, or notes...',
    'Tìm tiêu đề hoặc nội dung ghi chú...': 'Search note title or content...',
    'Tìm trong thư viện...': 'Search your library...',
    'Tôi đồng ý với ': 'I agree to ',
    'Trang chủ': 'Home',
    'Trang viết': 'Writing page',
    'Trợ lý AI': 'AI Study Assistant',
    'Trợ lý đang bận. Bạn thử gửi lại sau một chút nhé.':
        'The assistant is busy. Please try again shortly.',
    'Trợ lý học tập AI': 'AI Study Assistant',
    'Tùy chọn': 'Options',
    'Ví dụ (tùy chọn)': 'Example (optional)',
    'Ví dụ minh họa': 'Example',
    'Ví dụ minh họa (tùy chọn)': 'Example (optional)',
    'Vị trí ảnh đã sẵn sàng để kết nối kho ảnh.':
        'The image slot is ready to connect to storage.',
    'Vui lòng nhập định nghĩa': 'Please enter a definition',
    'Vui lòng nhập email': 'Please enter your email',
    'Vui lòng nhập email hợp lệ.': 'Please enter a valid email.',
    'Vui lòng nhập họ tên': 'Please enter your full name',
    'Vui lòng nhập mật khẩu': 'Please enter your password',
    'Vui lòng nhập tên bộ thẻ': 'Please enter a set name',
    'Vui lòng nhập thuật ngữ': 'Please enter a term',
    'Xác nhận mật khẩu': 'Confirm password',
    'Xây dựng một bộ thẻ có cấu trúc rõ ràng để việc ôn tập nhẹ nhàng hơn.':
        'Build a well-structured set for easier study sessions.',
    'Xem kết quả': 'View results',
    'Xem tất cả': 'View all',
    'Xóa': 'Delete',
    'Xóa bộ flashcard?': 'Delete flashcard set?',
    'Xóa bộ thẻ': 'Delete set',
    'Xóa cuộc trò chuyện?': 'Clear conversation?',
    'Xóa ghi chú': 'Delete note',
    'Xóa ghi chú?': 'Delete note?',
    'Xóa thẻ': 'Delete card',
    'Xóa thẻ này?': 'Delete this card?',
    'Xóa trang vẽ': 'Clear drawing',
    'Xóa trò chuyện': 'Clear conversation',
    'Yêu cầu đã được ghi nhận.': 'Request received.',
    'Chia sẻ bộ flashcard': 'Share flashcard set',
    'Chia sẻ ghi chú': 'Share note',
    'Đã gửi yêu cầu phát âm nội dung thẻ.': 'Pronunciation request sent.',
    'Định nghĩa': 'Definition',
    'Khôi phục mật khẩu': 'Reset password',
    'Learning Card App · Phiên bản 1.0.0': 'Learning Card App · Version 1.0.0',
    'Thuật ngữ': 'Term',
    'Xóa tìm kiếm': 'Clear search',
  };

  static const _japanese = <String, String>{
    'AI học tập': 'AI学習',
    'AI Study Assistant': 'AI学習アシスタント',
    'Bạn cần đồng ý với điều khoản để tiếp tục.': '続行するには利用規約に同意してください。',
    'Bằng cách tiếp tục, bạn đồng ý với Điều khoản sử dụng.':
        '続行すると、利用規約に同意したことになります。',
    'Bắt đầu bộ thẻ đầu tiên': '最初の単語カードを作成',
    'Bắt đầu miễn phí và đồng bộ tiến độ trên mọi thiết bị.':
        '無料で始めて、すべての端末で進捗を同期。',
    'Bật đồng hồ': 'タイマーをオン',
    'Bộ flashcard': '単語カードセット',
    'Bộ flashcard cần ít nhất một thẻ.': 'セットには1枚以上のカードが必要です。',
    'Bộ flashcard học tập': '学習用単語カード',
    'Bộ thẻ chưa có nội dung': 'このセットにはまだカードがありません',
    'Bộ thẻ gần đây': '最近のセット',
    'Bút': 'ペン',
    'Cài đặt': '設定',
    'Cập nhật ghi chú': 'ノートを更新',
    'Câu tiếp theo': '次の問題',
    'Chạm để lật · Vuốt để chuyển thẻ': 'タップで裏返す · スワイプで移動',
    'Chạm để quay lại thuật ngữ': 'タップして用語に戻る',
    'Chạm vào thẻ để xem đáp án': 'カードをタップして答えを表示',
    'Chào mừng\ntrở lại.': 'おかえり\nなさい。',
    'Chế độ học': '学習モード',
    'Chế độ tối': 'ダークモード',
    'Chỉ bạn và người được mời có thể xem': '自分と招待された人だけが閲覧できます',
    'Chi tiết bộ thẻ': 'セットの詳細',
    'Chia sẻ': '共有',
    'Chia sẻ bộ thẻ': 'セットを共有',
    'Chia sẻ quyền xem': '閲覧権限を共有',
    'Chỉnh sửa': '編集',
    'Chỉnh sửa bộ thẻ': 'セットを編集',
    'Chỉnh sửa hồ sơ': 'プロフィールを編集',
    'Chỉnh sửa thẻ': 'カードを編集',
    'Chỉnh sửa thông tin': '情報を編集',
    'Chính xác!': '正解！',
    'CHỌN ĐỊNH NGHĨA ĐÚNG': '正しい定義を選択',
    'Chọn ngôn ngữ': '言語を選択',
    'Chủ đề': '科目',
    'Chưa chia sẻ riêng với tài khoản nào.': 'まだ誰とも個別共有していません。',
    'Chưa có bộ thẻ': '単語カードがありません',
    'Chưa có ghi chú nào': 'ノートがありません',
    'Chưa có tài khoản?': 'アカウントをお持ちでないですか？',
    'Chưa có thẻ để học': '学習するカードがありません',
    'Chưa mở được sổ tay': 'ノートを開けませんでした',
    'Chưa mở khóa': '未解除',
    'Chưa nhớ': '覚えていない',
    'Chưa tải được danh sách chia sẻ.': '共有リストを読み込めませんでした。',
    'Chưa tải được Dashboard': 'ダッシュボードを読み込めませんでした',
    'Chưa tải được nội dung': '内容を読み込めませんでした',
    'Chưa thể cập nhật bộ thẻ.': 'セットを更新できませんでした。',
    'Chưa thể cập nhật thẻ lúc này.': '現在カードを更新できません。',
    'Chưa thể lưu bộ thẻ. Vui lòng thử lại.': 'セットを保存できません。もう一度お試しください。',
    'Chưa thể lưu ghi chú. Vui lòng thử lại.': 'ノートを保存できません。もう一度お試しください。',
    'Chưa thể lưu thẻ. Vui lòng thử lại.': 'カードを保存できません。もう一度お試しください。',
    'Chưa thể tạo bài quiz': 'クイズを作成できません',
    'Chưa thể tạo tài khoản. Vui lòng thử lại.': 'アカウントを作成できません。もう一度お試しください。',
    'Chưa thể thay đổi quyền riêng tư.': '公開設定を変更できません。',
    'Chưa thể xóa bộ thẻ lúc này.': '現在セットを削除できません。',
    'Chưa thể xóa ghi chú lúc này.': '現在ノートを削除できません。',
    'Chưa thể xóa thẻ lúc này.': '現在カードを削除できません。',
    'Chưa tìm kiếm được': '検索できませんでした',
    'Công khai': '公開',
    'Công nghệ': 'テクノロジー',
    'Của bạn': '自分のもの',
    'Đã cập nhật bộ thẻ.': 'セットを更新しました。',
    'Đã cấp quyền xem.': '閲覧権限を付与しました。',
    'Đã có tài khoản?': 'すでにアカウントをお持ちですか？',
    'Đã lưu nháp': '下書きを保存しました',
    'Đã lưu thay đổi.': '変更を保存しました。',
    'Đã lưu vào sổ tay.': 'ノートに保存しました。',
    'Đã nhớ': '覚えた',
    'Đã tạo bộ flashcard mới.': '新しいセットを作成しました。',
    'Đã thêm thẻ mới.': '新しいカードを追加しました。',
    'Đã thu hồi quyền truy cập.': 'アクセス権を取り消しました。',
    'Đã xóa bộ thẻ.': 'セットを削除しました。',
    'Đã xóa ghi chú.': 'ノートを削除しました。',
    'Đã xóa thẻ.': 'カードを削除しました。',
    'Đang chỉnh sửa ghi chú của bạn': 'ノートを編集中',
    'Đang chuẩn bị không gian học tập': '学習スペースを準備中',
    'Đang có quyền truy cập': 'アクセスできるユーザー',
    'Đăng ký': '登録',
    'Đang lưu...': '保存中...',
    'Đăng nhập': 'ログイン',
    'Đang tìm trong bộ thẻ, từng thẻ nhớ và ghi chú...': 'セット、カード、ノートを検索中...',
    'Đăng xuất': 'ログアウト',
    'Đăng xuất?': 'ログアウトしますか？',
    'Danh sách từ vựng': 'カード一覧',
    'Điều khoản sử dụng và Chính sách riêng tư': '利用規約とプライバシーポリシー',
    'Đính kèm ghi chú': 'ノートを添付',
    'ĐỊNH NGHĨA': '定義',
    'Định nghĩa hoặc câu trả lời': '定義または回答',
    'Dữ liệu học tập của riêng bạn': '自分専用の学習データ',
    'Đúng hôm nay': '今日の正答率',
    'Được chia sẻ': '共有済み',
    'Được tính từ các phiên học bạn đã hoàn thành': '完了した学習セッションから算出',
    'Email': 'メール',
    'Email chưa đúng định dạng': 'メール形式が正しくありません',
    'Email hoặc mật khẩu chưa đúng. Bạn thử lại nhé.': 'メールまたはパスワードが正しくありません。',
    'Email người nhận': '受信者のメール',
    'Flashcard, ghi chú và trợ lý AI trong một không gian học tập tập trung.':
        '単語カード、ノート、AIを一つの学習スペースに。',
    'Gần đúng rồi': 'もう少し',
    'Ghi chú': 'ノート',
    'Ghi chú chưa đặt tên': '無題のノート',
    'Ghi chú đã lưu': '保存済みノート',
    'Ghi chú được chia sẻ ở chế độ chỉ đọc': '共有ノートは読み取り専用です',
    'Ghi chú mới': '新しいノート',
    'Ghi chú viết tay': '手書きノート',
    'Ghi lại điều đáng nhớ': '大切なことを記録',
    'Ghi nhớ': '記憶',
    'Ghi nhớ sâu hơn. Học tập tinh tế hơn.': '深く覚え、美しく学ぶ。',
    'Giải thích, tóm tắt và tạo quiz': '説明、要約、クイズ作成',
    'Giảm chói khi học trong môi trường tối': '暗い場所でのまぶしさを軽減',
    'Giữ lại': '残す',
    'Gửi': '送信',
    'Gửi hướng dẫn': '案内を送信',
    'Hãy kiểm tra backend và migration dữ liệu rồi thử lại.':
        'バックエンドとDB移行を確認して、もう一度お試しください。',
    'Hãy kiểm tra kết nối và thử tải lại.': '接続を確認して再読み込みしてください。',
    'Hãy liên hệ thuật ngữ với định nghĩa này để ghi nhớ lâu hơn.':
        '用語と定義を結び付けて長く覚えましょう。',
    'Hãy thêm ít nhất một thẻ trước khi bắt đầu học.': '学習前にカードを1枚以上追加してください。',
    'Hãy thêm nội dung vào bộ flashcard rồi quay lại.':
        'セットにカードを追加してから戻ってください。',
    'Hãy thêm thẻ trước khi tạo bài quiz.': 'クイズ作成前にカードを追加してください。',
    'Hồ sơ': 'プロフィール',
    'Hồ sơ học tập': '学習プロフィール',
    'Họ và tên': '氏名',
    'Hoàn tác': '元に戻す',
    'Hoàn tất': '完了',
    'Hoàn thành bài quiz': 'クイズ完了',
    'Hoàn thành hôm nay': '今日の目標達成',
    'Hoàn thành phiên học': '学習セッション完了',
    'Hoạt động hôm nay': '今日のアクティビティ',
    'Học lại': 'もう一度学習',
    'Học ngay': '今すぐ学習',
    'Hỏi AI về bài học của bạn...': '学習内容をAIに質問...',
    'Hơi nhớ': '学習中',
    'Hôm nay bạn muốn\nhọc điều gì?': '今日は何を\n学びますか？',
    'Hủy': 'キャンセル',
    'Kết nối đang gián đoạn. Bạn thử lại nhé.': '接続が中断されました。もう一度お試しください。',
    'Kết nối đang gián đoạn. Hãy thử lại.': '接続が中断されました。再試行してください。',
    'Kết quả được lọc ngay theo tiêu đề, nội dung và người tạo.':
        'タイトル、内容、作成者で即時絞り込み。',
    'Kết quả xuất hiện ngay bên dưới ô tìm kiếm': '検索結果は検索欄のすぐ下に表示されます',
    'Khác': 'その他',
    'Khó': '難しい',
    'Khoa học': '科学',
    'Không có đáp án phù hợp': '該当する回答がありません',
    'Không có kết quả': '結果がありません',
    'Không thể mở thư viện': 'ライブラリを開けませんでした',
    'Không tìm thấy bộ thẻ': 'セットが見つかりません',
    'Không tìm thấy ghi chú': 'ノートが見つかりません',
    'Không tìm thấy tài khoản hoặc chưa thể chia sẻ.': 'アカウントが見つからないか、共有できません。',
    'Không tìm thấy trong dữ liệu của bạn, nội dung được chia sẻ hoặc công khai.':
        '自分のデータ、共有、公開コンテンツに該当がありません。',
    'Khu vực đính kèm đã sẵn sàng để kết nối.': '添付エリアは接続準備ができています。',
    'Kiến thức của bạn,\nđược tổ chức đẹp đẽ.': '知識を\n美しく整理。',
    'Kinh tế': '経済',
    'Làm lại': 'やり直す',
    'Lưu bộ flashcard': 'セットを保存',
    'Lưu ghi chú': 'ノートを保存',
    'Lưu thay đổi': '変更を保存',
    'Lưu thẻ': 'カードを保存',
    'Mặc định chỉ bạn nhìn thấy. Người được chia sẻ chỉ có quyền xem và học.':
        '初期設定は非公開。共有相手は閲覧と学習のみ可能です。',
    'Mật khẩu': 'パスワード',
    'Mật khẩu cần ít nhất 6 ký tự': 'パスワードは6文字以上必要です',
    'Mật khẩu xác nhận chưa khớp': 'パスワードが一致しません',
    'MẶT SAU': '裏面',
    'MẶT TRƯỚC': '表面',
    'Màu nhận diện': 'セットカラー',
    'Mình có thể giải thích khái niệm, tạo flashcard, tạo quiz hoặc tóm tắt ghi chú.':
        '概念の説明、カードやクイズの作成、ノートの要約ができます。',
    'Mở ghi chú': 'ノートを開く',
    'Mô tả': '説明',
    'Mở thư viện': 'ライブラリを開く',
    'Mọi người có thể tìm thấy tài nguyên này.': '誰でもこのリソースを見つけられます。',
    'Mọi tài khoản có thể tìm và xem': 'すべてのユーザーが検索・閲覧可能',
    'Một câu giúp ghi nhớ theo ngữ cảnh': '文脈で覚えるための例文',
    'Một khái niệm khác': '別の概念',
    'Một thẻ tốt nên ngắn gọn ở mặt trước và rõ ràng ở mặt sau.':
        '良いカードは表面を簡潔に、裏面を明確にします。',
    'Mục tiêu hoặc nội dung chính của bộ thẻ': 'セットの目的または主な内容',
    'Ngoại ngữ': '外国語',
    'Ngôn ngữ': '言語',
    'Người học': '学習者',
    'Nội dung mặt sau': '裏面の内容',
    'Nội dung mặt trước': '表面の内容',
    'Nội dung thẻ': 'カード内容',
    'Ở lại': '戻る',
    'Phát âm': '発音',
    'Quên mật khẩu?': 'パスワードを忘れた場合',
    'Quiz': 'クイズ',
    'Riêng tư': '非公開',
    'Sẵn sàng hỗ trợ': 'サポート準備完了',
    'Sổ tay học tập': '学習ノート',
    'Tài nguyên đã chuyển về riêng tư.': 'リソースを非公開にしました。',
    'Tạo bộ đầu tiên hoặc mở một bộ được chia sẻ với bạn.':
        '最初のセットを作成するか、共有セットを開いてください。',
    'Tạo bộ flashcard': '単語カードセットを作成',
    'Tạo bộ flashcard đầu tiên để bắt đầu học có hệ thống.':
        '最初のセットを作成して体系的に学習しましょう。',
    'Tạo bộ thẻ': 'セットを作成',
    'Tạo bộ thẻ hoặc mở nội dung được chia sẻ': 'セットを作成するか共有コンテンツを開く',
    'Tạo không gian\nhọc của riêng bạn.': '自分だけの\n学習スペースを作成。',
    'Tạo tài khoản': 'アカウント作成',
    'Tạo tài khoản mới': '新規アカウント作成',
    'Tạo tài khoản thành công. Hãy đăng nhập!': 'アカウントを作成しました。ログインしてください！',
    'Tạo trang viết đầu tiên để lưu lại ý tưởng và kiến thức.':
        '最初のページを作成して、アイデアや知識を保存しましょう。',
    'Tất cả': 'すべて',
    'Tắt đồng hồ': 'タイマーをオフ',
    'Tẩy': '消しゴム',
    'Tên bộ flashcard': 'セット名',
    'Tên bộ thẻ': 'セット名',
    'Tên bộ thẻ không được để trống': 'セット名は必須です',
    'Thành tích': '実績',
    'Thẻ': 'カード',
    'Thẻ đã học': '学習済みカード',
    'Thẻ đã thực sự học': '実際に学習したカード',
    'Thẻ nhớ': '単語カード',
    'Thêm hình ảnh': '画像を追加',
    'Thêm mô tả hoặc ghi chú dạng text...': '説明またはテキストノートを追加...',
    'Thêm thẻ': 'カードを追加',
    'Thêm thẻ đầu tiên': '最初のカードを追加',
    'Thêm thẻ khác': '別のカードを追加',
    'Thêm thẻ mới': '新しいカードを追加',
    'Thêm thuật ngữ đầu tiên để bắt đầu phiên học.': '最初の用語を追加して学習を始めましょう。',
    'Thông tin bộ thẻ': 'セット情報',
    'Thu hồi quyền': 'アクセスを取り消す',
    'Thử lại': '再試行',
    'Thử tìm kiếm bằng một từ khóa khác.': '別のキーワードで検索してください。',
    'Thư viện đang trống': 'ライブラリは空です',
    'Thư viện flashcard': '単語カードライブラリ',
    'THUẬT NGỮ': '用語',
    'Thuật ngữ hoặc câu hỏi': '用語または質問',
    'Tiến độ đã đồng bộ vẫn được lưu an toàn trong tài khoản.':
        '同期済みの進捗はアカウントに安全に保存されます。',
    'Tiếp tục hành trình học tập của bạn.': '学習を続けましょう。',
    'TIẾP TỤC HỌC': '学習を続ける',
    'Tiêu đề ghi chú': 'ノートのタイトル',
    'Tìm bộ thẻ, thuật ngữ hoặc ghi chú...': 'セット、用語、ノートを検索...',
    'Tìm tiêu đề hoặc nội dung ghi chú...': 'ノートのタイトルや内容を検索...',
    'Tìm trong thư viện...': 'ライブラリを検索...',
    'Tôi đồng ý với ': '同意します：',
    'Trang chủ': 'ホーム',
    'Trang viết': '書き込みページ',
    'Trợ lý AI': 'AI学習アシスタント',
    'Trợ lý đang bận. Bạn thử gửi lại sau một chút nhé.':
        'アシスタントは対応中です。少し後でもう一度お試しください。',
    'Trợ lý học tập AI': 'AI学習アシスタント',
    'Tùy chọn': 'オプション',
    'Ví dụ (tùy chọn)': '例（任意）',
    'Ví dụ minh họa': '例',
    'Ví dụ minh họa (tùy chọn)': '例（任意）',
    'Vui lòng nhập định nghĩa': '定義を入力してください',
    'Vui lòng nhập email': 'メールを入力してください',
    'Vui lòng nhập email hợp lệ.': '有効なメールを入力してください。',
    'Vui lòng nhập họ tên': '氏名を入力してください',
    'Vui lòng nhập mật khẩu': 'パスワードを入力してください',
    'Vui lòng nhập tên bộ thẻ': 'セット名を入力してください',
    'Vui lòng nhập thuật ngữ': '用語を入力してください',
    'Xác nhận mật khẩu': 'パスワード確認',
    'Xây dựng một bộ thẻ có cấu trúc rõ ràng để việc ôn tập nhẹ nhàng hơn.':
        '構造の明確なセットを作り、学習をよりスムーズに。',
    'Xem kết quả': '結果を見る',
    'Xem tất cả': 'すべて表示',
    'Xóa': '削除',
    'Xóa bộ flashcard?': 'セットを削除しますか？',
    'Xóa bộ thẻ': 'セットを削除',
    'Xóa cuộc trò chuyện?': '会話を削除しますか？',
    'Xóa ghi chú': 'ノートを削除',
    'Xóa ghi chú?': 'ノートを削除しますか？',
    'Xóa thẻ': 'カードを削除',
    'Xóa thẻ này?': 'このカードを削除しますか？',
    'Xóa trang vẽ': '描画を消去',
    'Xóa trò chuyện': '会話を削除',
    'Yêu cầu đã được ghi nhận.': 'リクエストを受け付けました。',
    'Chia sẻ bộ flashcard': '単語カードセットを共有',
    'Chia sẻ ghi chú': 'ノートを共有',
    'Đã gửi yêu cầu phát âm nội dung thẻ.': '発音リクエストを送信しました。',
    'Định nghĩa': '定義',
    'Khôi phục mật khẩu': 'パスワードを再設定',
    'Learning Card App · Phiên bản 1.0.0': 'Learning Card App · バージョン 1.0.0',
    'Thuật ngữ': '用語',
    'Xóa tìm kiếm': '検索をクリア',
  };

  static String translate(String source, AppLanguage language) {
    if (language == AppLanguage.vi || source.isEmpty) return source;
    final dictionary = language == AppLanguage.en ? _english : _japanese;
    final exact = dictionary[source];
    if (exact != null) return exact;

    var result = source;
    final replacements = language == AppLanguage.en
        ? const <String, String>{
            'Tạo bởi ': 'Created by ',
            'Bạn tạo': 'Created by you',
            ' thẻ trong bản nháp': ' draft cards',
            ' bộ thẻ trong thư viện': ' sets in your library',
            ' bộ thẻ': ' sets',
            ' thẻ': ' cards',
            ' kết quả': ' results',
            ' của bạn': ' owned',
            ' được chia sẻ': ' shared',
            ' phiên': ' sessions',
            ' câu đúng': ' correct',
            ' câu sai': ' wrong',
            'Ví dụ: ': 'Example: ',
            'Chỉ đọc · ': 'Read-only · ',
            'Đáp án: ': 'Answer: ',
            'THẺ ': 'CARD ',
            ' THẺ': ' CARDS',
            ' câu trả lời đúng': ' correct answers',
            ' sẽ được xóa khỏi bộ flashcard.':
                ' will be removed from the flashcard set.',
            ' sẽ bị xóa vĩnh viễn.': ' will be permanently deleted.',
            ' và toàn bộ thẻ bên trong sẽ bị xóa. Thao tác này không thể hoàn tác.':
                ' and all cards inside will be deleted. This action cannot be undone.',
            'Đã gửi yêu cầu phát âm “': 'Pronunciation request sent for “',
            'Chia sẻ ': 'Share ',
          }
        : const <String, String>{
            'Tạo bởi ': '作成者: ',
            'Bạn tạo': '自分が作成',
            ' thẻ trong bản nháp': '枚の下書きカード',
            ' bộ thẻ trong thư viện': 'セット（ライブラリ内）',
            ' bộ thẻ': 'セット',
            ' thẻ': '枚',
            ' kết quả': '件の結果',
            ' của bạn': '件所有',
            ' được chia sẻ': '件共有',
            ' phiên': 'セッション',
            ' câu đúng': '問正解',
            ' câu sai': '問不正解',
            'Ví dụ: ': '例: ',
            'Chỉ đọc · ': '読み取り専用 · ',
            'Đáp án: ': '答え: ',
            'THẺ ': 'カード ',
            ' THẺ': '枚',
            ' câu trả lời đúng': '問正解',
            ' sẽ được xóa khỏi bộ flashcard.': 'を単語カードセットから削除します。',
            ' sẽ bị xóa vĩnh viễn.': 'を完全に削除します。',
            ' và toàn bộ thẻ bên trong sẽ bị xóa. Thao tác này không thể hoàn tác.':
                'と中のすべてのカードを削除します。この操作は元に戻せません。',
            'Đã gửi yêu cầu phát âm “': '発音リクエストを送信しました：“',
            'Chia sẻ ': '共有: ',
          };
    for (final entry in replacements.entries) {
      result = result.replaceAll(entry.key, entry.value);
    }
    if (language == AppLanguage.en) {
      result = result
          .replaceFirst('1 draft cards', '1 draft card')
          .replaceFirst('1 cards', '1 card')
          .replaceFirst('1 sets', '1 set')
          .replaceFirst('1 correct answers', '1 correct answer');
    }
    return result;
  }
}

extension LocalizedBuildContext on BuildContext {
  String tr(String source) {
    final language = watch<LanguageProvider>().language;
    return AppTranslator.translate(source, language);
  }
}
